#!/bin/sh
Version="lincut v1.0 (gamma)"


if [ -z $XDG_CONFIG_HOME]; then
    if [ -d "$HOME/.config" ]; then
        lincut_conf="$HOME/.config/lincut"
    else 
        mkdir "$HOME/.config" > /dev/null
        lincut_conf="$HOME/.config/lincut"
    fi
else
    lincut_conf="$XDG_CONFIG_HOME/lincut"
fi


build_conf() {
    conf="$lincut_conf/lincut.conf"
    echo "Version: $Version" > $conf 
    if [ $? -ne 0 ]; then
        echo "[$Version]: Error setting up: $conf\n"
    fi
}

version() {
    echo "[$Version]: Version: $Version"
}

init_lincut() {
    path="$lincut_conf"
    mkdir $path 2> /dev/null
    if [ $? -ne 0 ]; then
        echo "[$Version]: Already setup: $path\n"
    fi


    plugins="$lincut_conf/plugins"
    mkdir $plugins 2> /dev/null
    if [ $? -ne 0 ]; then
        echo "[$Version]: Already setup: $plugins\n"
    fi
    
    build_conf
}

pluglist() {
    ls "$lincut_conf/plugins/"
    if [ $? -ne 0 ]; then
        echo "[$Version]: Error listing plugins! Have you run \"lincut init\" or \"lincut conf\"?"
    fi
}

addplugin() {
    path="$lincut_conf/plugins/"

    cp $1 $path

    if [ $? -ne 0 ]; then
        echo "[$Version]: Error installing plugin! Have you run \"lincut init\" or \"lincut conf\"?"
    fi
}



if [ $# -lt 1 ]; then
    echo "[$Version] Usage: lincut <cmd> <args>\n\tDo \"lincut help\" for help."
    return 1

elif [ "$1" = "help" ]; then
    echo "[$Version]\n\
            Commands:\n\
                \thelp\tDisplays this help menu.\n\
                \tversion\tDisplays version.\n\
                \tinit\tInitilizes limcut and makes config files.\n\
                \tip\tInstall plugin, usage\"lincut ip <plugin to install>\"\n\
                \tlp\tList plugins.\n\
                \tconf\tBuild or rebuild (for updates), lincut configuration file.\n\
                \twc\tPrint location of configuration files.\n\
                \t<none>\tRun plugin."

elif [ "$1" = "ip" ]; then
    if [$# -lt 2]; then
        echo "No input specified!"
        return 2
    fi
    addplugin $2 

elif [ "$1" = "lp" ]; then
    pluglist

elif [ "$1" = "wc" ]; then
    echo "[$Version] Config files located at: $lincut_conf"

elif [ "$1" = "conf" ]; then
    build_conf

elif [ "$1" = "init" ]; then
    init_lincut
    return $?

elif [ "$1" = "version" ]; then
    version
    return $?

else
    conf="$lincut_conf/plugins/$1/plugin.conf"
    
    if [ ! -f "$conf" ]; then
        echo "[$Version]: Bad plugin.conf @ $conf"
        return 1
    fi
    
    trim_leading_spaces() {
        echo "$1" | sed 's/^[[:space:]]*//'
    }
    
    run=$(grep 'run\s*=' "$conf" | sed 's/^.*=//')
    run=$(trim_leading_spaces "$run")
    runwith=$(grep 'runwith\s*=' "$conf" | sed 's/^.*=//')
    runwith=$(trim_leading_spaces "$runwith")
    
    plugin="$lincut_conf/plugins/$1$run"

    #get args
    shift 1

    eval "$runwith $plugin $@"

fi
     