#!/bin/sh
Version="lincut v1.0 (gamma)"


if [ -z "$XDG_CONFIG_HOME" ]; then
   lincut_conf="$HOME/.config/lincut"
   mkdir -p "$lincut_conf"
else
    lincut_conf="$XDG_CONFIG_HOME/lincut"
fi


build_conf() {
    conf="$lincut_conf/lincut.conf"
    if ! echo "Version: " > "$conf"; then
        echo "[$Version]: Error setting up: $conf"
    fi
}

version() {
    echo "[$Version]: Version: $Version"
}

init_lincut() {
    path="$lincut_conf"
    if ! mkdir "$path" 2> /dev/null; then
        echo "[$Version]: Already setup: $path"
    fi


    plugins="$lincut_conf/plugins"
    if ! mkdir "$plugins" 2> /dev/null; then
        echo "[$Version]: Already setup: $plugins"
    fi
    
    build_conf
}

pluglist() {
    if ! ls "$lincut_conf/plugins/"; then
        echo "[$Version]: Error listing plugins! Have you run \"lincut init\" or \"lincut conf\"?"
    fi
}

addplugin() {
    path="$lincut_conf/plugins/"
    if ! cp -r "$1" "$path"; then
        echo "[$Version]: Error installing plugin! Have you run \"lincut init\" or \"lincut conf\"?"
    fi
}



if [ $# -lt 1 ]; then
    printf "[%s] Usage: lincut <cmd> <args>\n\tDo \"lincut help\" for help.\n" "$Version"
    return 1

elif [ "$1" = "help" ]; then
    printf "[%s]\n\
            Commands:\n\
                \thelp\tDisplays this help menu.\n\
                \tversion\tDisplays version.\n\
                \tinit\tInitilizes limcut and makes config files.\n\
                \tip\tInstall plugin, usage\"lincut ip <plugin to install>\"\n\
                \tlp\tList plugins.\n\
                \tconf\tBuild or rebuild (for updates), lincut configuration file.\n\
                \twc\tPrint location of configuration files.\n\
                \t<none>\tRun plugin.\n"\
                "$Version"

elif [ "$1" = "ip" ]; then
    if [ $# -lt 2 ]; then
        echo "No input specified!"
        return 2
    fi
    addplugin "$2"

elif [ "$1" = "lp" ]; then
    pluglist

elif [ "$1" = "wc" ]; then
    echo "[$Version] Config files located at: $lincut_conf"

elif [ "$1" = "conf" ]; then
    build_conf

elif [ "$1" = "init" ]; then
    init_lincut
    return $?

elif [ "$1" = "version" ]; then
    version
    return $?

else
    conf="$lincut_conf/plugins/$1/plugin.conf"
    
    if [ ! -f "$conf" ]; then
        echo "[$Version]: Bad plugin.conf @ $conf"
        return 1
    fi
    
    trim_leading_spaces() {
        echo "$1" | sed 's/^[[:space:]]*//'
    }
    
    run=$(grep 'run\s*=' "$conf" | sed 's/^.*=//')
    run=$(trim_leading_spaces "$run")
    runwith=$(grep 'runwith\s*=' "$conf" | sed 's/^.*=//')
    runwith=$(trim_leading_spaces "$runwith")
    
    plugin="$lincut_conf/plugins/$1$run"

    #get args
    shift 1

    eval "$runwith $plugin $*"

fi
     